"""empty message

Revision ID: 08f49b03e057
Revises: 
Create Date: 2026-03-05 17:41:47.494777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f49b03e057'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mu', sa.Float(), server_default='25.0', nullable=False))
        batch_op.add_column(sa.Column('sigma', sa.Float(), server_default='8.333', nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('elo_rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elo_rating', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.drop_column('sigma')
        batch_op.drop_column('mu')

    # ### end Alembic commands ###
