"""added description to match

Revision ID: 4778096908db
Revises: a7930d99adc9
Create Date: 2026-03-07 22:40:18.687871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4778096908db'
down_revision = 'a7930d99adc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'description')
    # ### end Alembic commands ###
