"""empty message

Revision ID: a7930d99adc9
Revises: dbb484a061a5
Create Date: 2026-03-07 22:28:04.804299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7930d99adc9'
down_revision = 'dbb484a061a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # first set nulls to 0
    op.execute('UPDATE team SET score = 0 WHERE score IS NULL')
    # then change the column
    op.alter_column('team', 'score',
        existing_type=sa.Integer(),
        nullable=False,
        server_default='0'
    )

    # ### end Alembic commands ###

    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
